name: Run Raspberry Pi Pico Script

# Trigger the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest  # The virtual machine where the script will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure the right Python version is installed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if you have any

      - name: Run Python Script
        env:
          FIREBASE_OAUTH_TOKEN: ${{ secrets.FIREBASE_OAUTH_TOKEN }}  # Use the secret
        run: |
          python your_script.py  # Replace this with your script filename
